name: daily-automatic-update

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

env:
  GH__USERNAME: ${{ secrets.GH__USERNAME }}
  GH__TOKEN: ${{ secrets.GH__TOKEN }}
  GIT__NAME: ${{ secrets.GIT__NAME }}
  GIT__EMAIL: ${{ secrets.GIT__EMAIL }}
  NUGET__TOKEN: ${{ secrets.NUGET__TOKEN }}
  GIT__TOKEN: ${{ secrets.GIT__TOKEN }}
  PipelineEnvironment: true
  NUGET_XMLDOC_MODE: skip

jobs:

  daily-automatic-update:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setting up build version
        run: |
          version=$(($GITHUB_RUN_NUMBER))
          echo "BUILD_VERSION=4.0.$version" >> ${GITHUB_ENV}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/Soenneker.Runners.FFmpeg/Soenneker.Runners.FFmpeg.csproj

      - name: Build
        run: dotnet build src/Soenneker.Runners.FFmpeg/Soenneker.Runners.FFmpeg.csproj --configuration Release --no-restore

      - name: Run
        run: dotnet run --project src/Soenneker.Runners.FFmpeg/Soenneker.Runners.FFmpeg.csproj --configuration Release --no-restore --no-build --verbosity normal
