name: daily-automatic-update
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.USERNAME }}
  TOKEN: ${{ secrets.TOKEN }}
  NAME: ${{ secrets.NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

jobs:

  daily-automatic-update:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Setting up build version
        run: |
          version=$(($GITHUB_RUN_NUMBER))
          echo "BUILD_VERSION=2.5.$version" >> ${GITHUB_ENV}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies with retry
        run: |
          retries=5
          base_wait_time=15
          exponent=2

          for i in $(seq 1 $retries); do
            if dotnet restore; then
              break
            fi

            if [ $i -lt $retries ]; then
              wait_time=$(awk "BEGIN {print int($base_wait_time * ($exponent ^ ($i - 1)))}")
              echo "dotnet restore failed, retrying in $wait_time seconds..."
              sleep $wait_time
            else
              echo "dotnet restore failed after $retries retries."
              exit 1
            fi
          done

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --project src/Soenneker.Runners.FFmpeg.csproj --no-restore --verbosity normal --framework net9.0
